### PR TITLE
fix: add forward declaration for struct Chip in C++ header

### LINKED ISSUE #8: `Chip` not defined in luwencpp's luwen.h header
Hi,

I'm building an AUR package for Luwen and subsequently tt-smi and other engineering tools. Currently the header generated by the luwencpp crate is not well-formed. Missing an forward deceleration of the `Chip` structure as of commit e4e10e95928f4b73d31ac4f41ea08cd6e3ef5573. Including the header causes compilation error:

```
➜  luwen-git g++ test.cpp
In file included from test.cpp:1:
/usr/include/luwen.h:105:1: error: ‘Chip’ does not name a type
  105 | Chip *luwen_open(Arch arch, LuwenGlue glue);
      | ^~~~
/usr/include/luwen.h:110:1: error: ‘Chip’ does not name a type
  110 | Chip *luwen_open_remote(Chip *local_chip, EthAddr addr);
      | ^~~~
/usr/include/luwen.h:115:6: error: variable or field ‘luwen_close’ declared void
  115 | void luwen_close(Chip *chip);
      |      ^~~~~~~~~~~
/usr/include/luwen.h:115:18: error: ‘Chip’ was not declared in this scope
  115 | void luwen_close(Chip *chip);
      |                  ^~~~
/usr/include/luwen.h:115:24: error: ‘chip’ was not declared in this scope
  115 | void luwen_close(Chip *chip);
      |                        ^~~~
/usr/include/luwen.h:117:28: error: ‘Chip’ does not name a type
  117 | CResult chip_arc_msg(const Chip *chip,
      |                            ^~~~
/usr/include/luwen.h:125:32: error: ‘Chip’ does not name a type
  125 | Telemetry chip_telemetry(const Chip *chip);
      |                                ^~~~
```

### PR DESCRIPTION
**Pull request by fabracht**
## Summary
- fixes compilation error where `struct Chip` was not forward-declared in the generated C++ header
- adds `struct Chip;` forward declaration using cbindgen's `with_after_include` directive
- includes test to verify the header compiles correctly with C++

fixes #8

### CODE REVIEW

File: tests/luwencpp_header_test.rs [hunk 1]
```diff
@@ -0,0 +1,97 @@
+#![cfg(test)]
```
Comment (DRvader) [inline tests/luwencpp_header_test.rs:1]: Could you move this test to the luwencpp directory? The reason that you need to run the build manually is that the root crate does not include luwencpp as a dependency. But making it a test of the package will avoid you needing to run that step.

File: crates/luwencpp/build.rs [hunk 2]
```diff
@@ -33,6 +33,7 @@ fn main() {
     let result = cbindgen::Builder::new()
         .with_pragma_once(true)
         .with_namespace("luwen")
+        .with_after_include("struct Chip;")
```
[the remark this answers is not in the document]
Comment (fabracht) [reply crates/luwencpp/build.rs:36]: I tried using the newtype pattern, but I got issues with cbindgen's handling of the newtype wrappers. Here's what I found:
Following your suggestion, I tried:

```rust
#[repr(transparent)]
pub struct Chip(luwen_if::chip::Chip);
```

plus the "plumbing" and the respective change needed in `pub extern "C" fn luwen_open`.
But when cbindgen processes this newtype pattern, it generates `using Chip = Chip;`, and this doesn't compile.
I tried some crazy shenanigans to see if I could make it work, but so far, I couldn't get rid of the forward declaration.
I was able to get something in between using a `cbindgen:no-export`. With cbindgen:no-export: we don't generate any definition for Chip, which makes the forward declaration from with_after_include("struct Chip;") only declaration. This gives us type safety at compilation time, but we still need the forward declaration.
I would appreciate your input here, maybe you know a more elegant solution. Thanks.

File: tests/luwencpp_header_test.rs [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+/// - Locating the generated luwen.h header file
+/// - Creating a temporary C++ test file that includes and uses the header
+/// - Compiling the test file with a C++ compiler
+/// - Verifying compilation succeeds without errors
+///
+/// Note: This test requires a C++ compiler to be available on the system.
+/// It will attempt to use 'c++' command which should be available on most
+/// Unix-like systems with a C++ compiler installed.
+
+mod tests {
```
[the remark this answers is not in the document]
Comment (fabracht) [reply tests/luwencpp_header_test.rs]: Removed it.

File: tests/luwencpp_header_test.rs (hunk 1 above)
Comment (fabracht) [reply tests/luwencpp_header_test.rs]: Moved

File: crates/luwencpp/src/lib.rs [hunk 4]
```diff
@@ -157,6 +156,19 @@ pub struct LuwenGlue {
     ),
 }
 
+/// Newtype wrapper for luwen_if::chip::Chip
+/// cbindgen:no-export
+#[repr(transparent)]
```
Comment (DRvader) [inline crates/luwencpp/src/lib.rs:161]: Removing these two lines will actually make a forward declared Chip struct like you want. You will probably just have to update the header_compilation_test so that it uses `luwen::Chip` instead of `::Chip`

File: crates/luwencpp/tests/header_compilation_test.rs [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+}
+
+int main() {
+    test_chip_forward_declaration();
+    return 0;
+}
+"#;
+
+    // Use temp directory for test files
+    let temp_dir = env::temp_dir();
```
Comment (DRvader) [inline crates/luwencpp/tests/header_compilation_test.rs:61]: On standard linux systems this function returns `/tmp` I would prefer creating a subdirectory to avoid polluting the /tmp dir with the build artifacts.

File: tests/luwencpp_header_test.rs [hunk 6]
```diff
@@ -0,0 +1,97 @@
...
+    use std::fs;
+    use std::path::Path;
+    use std::process::Command;
+
+    #[test]
+    fn test_header_compiles() {
+        // Find the generated header file
+        let header_path = if Path::new("target/debug/luwen.h").exists() {
```
[the remark this answers is not in the document]
Comment (DRvader) [reply tests/luwencpp_header_test.rs]: What was the reason you used the manifest path instead of the out dir variable?

File: crates/luwencpp/tests/header_compilation_test.rs [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+        "aarch64-unknown-linux-gnu"
+    } else if cfg!(target_os = "windows") && cfg!(target_arch = "x86_64") {
+        "x86_64-pc-windows-msvc"
+    } else {
+        panic!("Unsupported platform");
+    };
+
+    env::set_var("TARGET", target);
+    env::set_var("OPT_LEVEL", "0");
+    env::set_var("HOST", target);
```
Comment (DRvader) [inline crates/luwencpp/tests/header_compilation_test.rs:87]: You should be able to pull these out of the build script via writing them to a file in OUT_DIR behind a cfg flag so they aren't always written. You then should be able to set them directly via arguments to the cc::Build type.

Comment (DRvader) [reply crates/luwencpp/tests/header_compilation_test.rs:87]: If you find this path too convoluted then feel free to switch to your previous method I can add the cc method later if/when it matters.

File: crates/luwencpp/tests/header_compilation_test.rs [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+
+    // Use cc crate to compile the test file
+    let mut build = cc::Build::new();
+    build
```
Comment (DRvader) [inline crates/luwencpp/tests/header_compilation_test.rs:91]: Add an explicit output directory, that'll make it easier to find the file if a run step is later added.

**Review by DRvader — COMMENTED** [review]
Add great changes! Just have a few small tweaks before merging, but you have exactly the right idea!

File: crates/luwencpp/tests/header_compilation_test.rs (hunk 5 above)
Comment (fabracht) [reply crates/luwencpp/tests/header_compilation_test.rs:61]: Sorry, I didn't read your original comment properly. You had mentioned using the tempfile library, and not the temp_dir() call I used. My bad. I'm fixing it.

File: crates/luwencpp/src/lib.rs (hunk 4 above)
Comment (fabracht) [reply crates/luwencpp/src/lib.rs:161]: Ah, obviously...haha. Classic case of "keep it simple st....". Thanks, now I get it.

File: tests/luwencpp_header_test.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (fabracht) [reply tests/luwencpp_header_test.rs]: My bad, I wasn't aware that OUT_DIR was available in integration tests since Cargo 1.76.0 (or 77?) https://github.com/rust-lang/cargo/pull/13204. I thought it was only available in build scripts, so I used CARGO_MANIFEST_DIR as a fallback. But you're right - I could have used OUT_DIR to find the target directory, just like the build script does.

[the remark this answers is not in the document]
Comment (DRvader) [reply tests/luwencpp_header_test.rs]: It's a bit strange but OUT_DIR is available during compile time only if you have a build script. You can therefore use the fact that env! executes at compile time to pull that variable to our runtime

[the remark this answers is not in the document]
Comment (fabracht) [reply tests/luwencpp_header_test.rs]: Thanks for the info.
